# Generated by Django 6.0.5 on 2026-05-30 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.CharField(help_text='Ex: ferramentas-celular', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtítulo')),
                ('color', models.CharField(help_text='Classe CSS do Tailwind. Ex: bg-gradient-to-br from-blue-500 to-blue-600', max_length=100)),
                ('icon_svg', models.TextField(help_text='Código SVG completo do ícone principal')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.CharField(help_text='Ex: tirar-foto', max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Título do Tutorial')),
                ('desc', models.TextField(verbose_name='Descrição Curta')),
                ('icon', models.CharField(help_text='Nome do ícone no Lucide. Ex: camera, lock, phone', max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='main.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Passo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Número do Passo')),
                ('title', models.CharField(max_length=150, verbose_name='Título do Passo')),
                ('description', models.TextField(verbose_name='Instruções do Passo')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='Dica Importante (Opcional)')),
                ('icon_svg', models.TextField(blank=True, help_text='SVG opcional para o ícone interno do passo', null=True)),
                ('interactiveImage', models.CharField(blank=True, help_text='Caminho da imagem. Ex: /static/IMG/spam_suspeito.jpg', max_length=255, null=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main.tutorial', verbose_name='Tutorial')),
            ],
            options={
                'verbose_name': 'Passo do Tutorial',
                'verbose_name_plural': 'Passos do Tutorial',
                'ordering': ['ordem'],
            },
        ),
    ]
