# Generated by Django 6.0.6 on 2026-06-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_progresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='passo',
            name='html_interativo',
            field=models.TextField(blank=True, help_text="Código HTML/Tailwind que desenha o ecrã do telemóvel. Pode colocar onclick='handleNextStep()' no botão correto!", null=True, verbose_name='HTML Interativo'),
        ),
        migrations.AlterField(
            model_name='passo',
            name='interactiveImage',
            field=models.CharField(blank=True, help_text='Caminho da imagem estática. Ex: /static/IMG/spam_suspeito.jpg', max_length=255, null=True),
        ),
    ]
